### ISSUE TITLE
Refactor control state mixin to use new mixins

### ISSUE THREAD

**Issue by web-padawan** [vaadin/component-mixins#20]
Change `ControlStateMixin` to use the new mixins:

- `DisabledStateMixin` - #10 
- `FocusVisibleMixin` - #11 

Note: this would need `0.2.0` version bump.

**Comment by Haprog** [comment]
> Note: this would need 0.2.0 version bump.

Not necessarily since according to [SemVer item 4](https://semver.org/#spec-item-4):

> Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

But if it feels like a minor bump makes sense, then sure we can do it.
