### ISSUE TITLE
Polymer dependency

### ISSUE THREAD

**Issue by christophe-g** [vaadin/component-mixins#70]
I am not too sure how to phrase this without sounding like a too demanding jerk. 
I am well aware it is ~epic. Also, it is mentioned in different issues that it is not going to happen anytime soon. 

But anyway, removing Polymer dependency would be (really) nice. 

Not that I don't like Polymer, on the contrary, but it is currently not possible to use recent lit-element based Vaadin components in application running older version of Polymer (mostly because dom-module is registered twice, once for every Polymer version). 

Is there any plan to replace themable-mixin (I think the only reason for Polymer Dependency) with approaches tested by @jouni here: https://jelements.netlify.app/stylable-mixin ?

Thanks,
C.

**Comment by web-padawan** [comment]
> Is there any plan to replace themable-mixin (I think the only reason for Polymer Dependency) 

We are not going to remove `ThemableMixin` until all the components are also converted to LitElement. This might take significant amount of time for complex components like `vaadin-grid`, `vaadin-combo-box` and `vaadin-date-picker`.

Unfortunately, the Components team capacity is quite limited at the moment and there are other priorities.
